# Generated by Django 4.2 on 2023-05-14 06:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rink', models.URLField(max_length=1024, blank=True)),
                ('image', models.CharField(max_length=1024)),
                ('modelimage', models.CharField(max_length=1024)),
                ('gender', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),                
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('part', models.CharField(max_length=20)),
                ('season', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('brand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('price', models.IntegerField(default=0)),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('situation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('age', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('youtube', models.URLField(max_length=1024, blank=True)),
                ('blog', models.URLField(max_length=1024, blank=True)),
                ('y_name', models.CharField(max_length=255)),
                ('b_name', models.CharField(max_length=255)),
            ],
        ),
    ]
