# Generated by Django 4.2 on 2023-04-14 08:26

from django.db import migrations, models
import csv, os

def add_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    csv_file = "C:/Users/sin15/OneDrive/바탕 화면/r_data.csv"
    with open(csv_file, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            age_values = row[13].split(',') if row[13] else []  # 빈 문자열인 경우 빈 리스트로 처리
            age = [int(value) for value in age_values]  # 문자열을 정수로 변환
            user = User(
                id=int(row[0]),
                name=row[1],
                rink=row[2],
                image=row[3],
                modelimage=row[4],
                gender=row[5].split(','),
                color=row[6].split(','),
                part=row[7],
                season=row[8].split(','),
                brand=row[9].split(','),
                price=int(row[10]),
                tag=row[11].split(','),
                situation=row[12].split(','),
                age=age,  # 정수 리스트로 변환된 값 사용
                youtube=row[14],
                blog=row[15],
                y_name=row[16],
                b_name=row[17],
                score=int(row[18])
            )
            user.full_clean()
            user.save()
 
  
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(add_users),
    ]