# Generated by Django 4.2 on 2023-04-14 08:26

from django.db import migrations, models
import csv, os

def add_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    csv_file = "C:/Users/sin15/OneDrive/바탕 화면/cl_data.csv"#os.path.expanduser("~/Desktop/cl_data.csv")
    with open(csv_file, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            user = User(
                id=row[0],
                name=row[1],
                rink=row[2],
                image = row[3],
                gender = row[4].split(','),
                color = row[5].split(','),
                part=row[6],
                season=row[7].split(','),
                brand=row[8],
                price=row[9],
                tag=row[10].split(','),
                youtube=row[11],
                score=row[12]
            )
            user.full_clean() # 데이터 유효성 검사
            user.save()  
  
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(add_users),
    ]
